version: "3.9"
services:
    frontend:
        build: .
        ports:
            - "8000:8000"
        depends_on:
            - backend
        volumes:
            - ./results/:/app/results/

    backend:
        image: postgres
        volumes:
            - ./mounts/postgres/:/var/lib/postgresql/data/
            - ./mounts/sockets/:/var/run/postgresql/
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: DataBase
            POSTGRES_DB: apidb
        ports:
            - "5433:5433"

