version: "3.9"
services:
    frontend:
        build: .
        ports:
            - "8000:8000"
        depends_on:
            - backend
        volumes:
            - ./results/:/app/results/

    backend:
        image: postgres
        volumes:
            - /var/lib/postgresql/16/:/var/lib/postgresql/data/
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: DataBase
            POSTGRES_DB: apidb
        ports:
            - "5432:5432"

