name: "sonar_cloud_scan_fastAPI"
on:
  workflow_dispatch:

jobs:
  DemoSonarCloudSCan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
            fetch-depth: 0
      - name: SonarCloudScan
        uses: sonarsource/sonarcloud-github-action@master
        env:
            GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
              -Dsonar.organization=meiyor
              -Dsonar.projectKey=ABIChallenge_Juan_Manuel_Mayor_Torres
              -Dsonar.python.coverage.reportPaths=coverage.xml
